#!/bin/bash

apt-get install harden-environment arno-iptables-firewall rcconf -y

# Issue w/ tiger config
ln -s /usr/lib/tiger/systems/Linux/2 /usr/lib/tiger/systems/Linux/3

dpkg-reconfigure arno-iptables-firewall



# vim /etc/logcheck
# change logcheck cron in /etc/cron.d/logcheck to * 0 * * *   (daily)
