#!/bin/bash

# clear quarantine/session/tmp data every 14 days
/usr/sbin/tmpwatch 336 /usr/local/maldetect/tmp >> /dev/null 2>&1
/usr/sbin/tmpwatch 336 /usr/local/maldetect/sess >> /dev/null 2>&1
/usr/sbin/tmpwatch 336 /usr/local/maldetect/quarantine >> /dev/null 2>&1
/usr/sbin/tmpwatch 336 /usr/local/maldetect/pub/*/ >> /dev/null 2>&1

# check for new release version
/usr/local/maldetect/maldet -d >> /dev/null 2>&1

# check for new definition set
/usr/local/maldetect/maldet -u >> /dev/null 2>&1

# if were running inotify monitoring, send daily hit summary
if [ "$(ps -A --user root -o "comm" | grep inotifywait)" ]; then
        /usr/local/maldetect/maldet --alert-daily >> /dev/null 2>&1
else
	# scan the last 2 days of file changes
	if [ -d "/sites" ]; then
		# ensim
	        /usr/local/maldetect/maldet -b -r /sites 2 >> /dev/null 2>&1
	elif [ -d "/home" ]; then
		# psa
		/usr/local/maldetect/maldet -b -r /home 2 >> /dev/null 2>&1
	fi

	# scan default apache docroot paths
	if [ -d "/var/www" ]; then
		/usr/local/maldetect/maldet -b -r /var/www 2
	fi
	if [ -d "/usr/local/apache" ]; then
		/usr/local/maldetect/maldet -b -r /usr/local/apache 2
	fi
fi

